### ISSUE TITLE
Unable to Detect iOS 8 or 9

### ISSUE THREAD

**Issue by emwalters** [ded/bowser#102]
I have a PhoneGap application that displays a “platform not supported” banner on the login page when Bowser detects a browser that does not fit my criteria of supported platform and supported version.
My base logic is set up like this:

var isSupported = Bowser[platform] && Bowser.version >= minSupportedVersion;

where:
Bowser[‘ios’] && Bowser.version >= '8'

But when I use an iPad with any of these user agents:
Mozilla/5.0 (iPad; CPU OS 9_0_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13A452
Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H143
Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H321

isSupported is set to false, and the user is erroneously shown that they are using an unsupported browser.  This behavior does not present itself when I’m detecting traditional desktop browsers like Chrome or Internet Explorer (the library correctly detects these platforms).

Is something in my logic incorrect, or is the library not reporting something correctly?

**Comment by lolmaus** [comment]
Have tried on a real iPhone with iOS 9.0.2 and Bowser reported it as `'iPhone'` and `'9.0'`.

Can you please report what exactly `Bowser.name` and `Bowser.version` it reports for you?

**Comment by lancedikson** [comment]
Is there the problem now?

**Comment by emwalters** [comment]
I'm no longer using bowser on that project, so I'm not sure.  Sorry.
