### ISSUE TITLE
Vivaldi browser shows up as Chrome

### ISSUE THREAD

**Issue by pokono** [ded/bowser#103]
Vivaldi browser shows up as Chrome version 44.

**Comment by NicolasBoaFritz** [comment]
User agent example, please?

**Comment by ded** [comment]
Oh my, as if a spinoff of Opera really needed to happen. Nevertheless, would you mind adding in a sample user agent string?

**Comment by pokono** [comment]
MAC:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.75 Safari/537.36 Vivaldi/1.0.219.53

WINDOWS:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.75 Safari/537.36 Vivaldi/1.0.219.50

I started putting the headers in this fork but I haven't had the time to finish the job, if it can be of any help it's here:
https://github.com/pokono/bowser/tree/vivaldi-support

Thank you!

**Comment by ded** [comment]
looks like it's on the right track. Did it pass the tests?

**Comment by pokono** [comment]
Submitted pull request #119.

**Comment by pokono** [comment]
@ded Sorry for the mess. I've closed the #119 as it was branched off an old master. I've submitted #120 which passes all the tests.

**Comment by lancedikson** [comment]
Merged. Thank you, @pokono 👍
