### ISSUE TITLE
Amazon Silk identified as Chrome

### ISSUE THREAD

**Issue by lippok** [ded/bowser#115]
The Amazon Slik Browser has a "like chrome" in the user agent string, so 

else if (/silk/i.test(ua)) {

must be before

else if (/chrome|crios|crmo/i.test(ua)) {

**Comment by lancedikson** [comment]
@lippok could you provide a UA of that browser?

**Comment by lancedikson** [comment]
But, wait, I got. It will be released in the next hotfix release
