### ISSUE TITLE
Detecting UA 

### ISSUE THREAD

**Issue by whizkydee** [ded/bowser#121]
Hello,
Please how do i detect User Agents with bowser. For example windows

**Comment by lancedikson** [comment]
@whizkydee, I'm sorry, I don't understand what's your question. Don't you get how to use it?

**Comment by whizkydee** [comment]
@lancedikson Thanks, I know how to detect browsers with this library. But i don't know how to detect operating systems like Windows, Mac, Linux.

**Comment by lancedikson** [comment]
@whizkydee, ok, please, look at the readme https://github.com/ded/bowser/tree/develop#os-flags. Is it clearer now or still not?

**Comment by whizkydee** [comment]
@lancedikson I don't still understand.

**Comment by whizkydee** [comment]
@lancedikson To detect the browser name.. We run `bowser.name`. So to detect the OS what do we run.

**Comment by lancedikson** [comment]
@whizkydee, ok, then I'm trying to explain. You can use those flags:
```
if (bowser.windows) {
  console.log('It's Windows!');
} else if ( bowser.mac) {
  console.log('It's Mac!');
}
```

**Comment by whizkydee** [comment]
`if (bowser.windows) {
  console.log('It\'s Windows!');
} else if ( bowser.mac) {
  console.log('It\'s Mac!');
}`

**Comment by lancedikson** [comment]
@whizkydee yep, you're right, sorry for misleading with quotes :)

**Comment by lancedikson** [comment]
@whizkydee, so, looks like you don't use Windows :)

**Comment by whizkydee** [comment]
@lancedikson i use windows... in fact i've tried on three PCs

**Comment by lancedikson** [comment]
@whizkydee hmm, weird, what's version of bowser do you use now? Which file of the repo?

**Comment by whizkydee** [comment]
Check this: [http://webtwic.github.io/js/libs/bowser.min.js](http://webtwic.github.io/js/libs/bowser.min.js)

**Comment by whizkydee** [comment]
@lancedikson I'll try updating the script now to see if it works

**Comment by lancedikson** [comment]
@whizkydee, try this one, please: https://github.com/ded/bowser/blob/develop/src/bowser.js. But you should care about minification by yourself.

**Comment by whizkydee** [comment]
@lancedikson thanks i'll try it.. I used: https://github.com/ded/bowser/blob/master/bowser.min.js

**Comment by whizkydee** [comment]
Oh... Thanks so much @lancedikson for your time. It now works pretty fine.
