### ISSUE TITLE
Failure detecting Safari mobile on iPad and iPhone

### ISSUE THREAD

**Issue by dmatteo** [ded/bowser#122]
Hey there,
we noticed an issue while trying to polyfill some validation for Safari.
Everything works as expected on desktop, but it fails to detect Safari (e.g. Chrome works fine) on mobile.

**Safari on iOS**
```
browser.safari === undefined
browser.ios === true
```

**Chrome on iOS**
```
browser.chrome === true
browser.ios === true
```

/cc @Anifacted

**Comment by CodingMonkeyzh** [comment]
I have noticed this issue too.
It looks like caused by following code at [bowser.js#L95-L103:](https://github.com/ded/bowser/blob/master/bowser.js#L95-L103)
```
    else if (iosdevice) {
      result = {
        name : iosdevice == 'iphone' ? 'iPhone' : iosdevice == 'ipad' ? 'iPad' : 'iPod'
      }
      // WTF: version is not part of user agent in web apps
      if (versionIdentifier) {
        result.version = versionIdentifier
      }
    }
```

**Comment by lancedikson** [comment]
related to #55
