### ISSUE TITLE
IE 10 and below breaks

### ISSUE THREAD

**Issue by mattnorris** [ded/bowser#123]
Base 64 encoding breaks on IE10 and below.

![screen shot 2016-01-25 at 2 52 40 pm](https://cloud.githubusercontent.com/assets/2898571/12567382/a0ad666e-c373-11e5-9af7-34ac566473cd.png)

**Comment by trbrc** [comment]
I might be missing something here but it looks like the `const` statement is the issue here? IE10 does not support ES2015.

**Comment by lancedikson** [comment]
We don't use base64 anywhere in the bowser
