### ISSUE TITLE
Looks like bowser is not properly detecting latest version of Edge

### ISSUE THREAD

**Issue by bmueller-sykes** [ded/bowser#129]
This could be a bug as of today (March 17, 2016). Latest version of Edge reports this:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64)`

...and even BrowserHawk appears to be incorrectly reporting this as well, FWIW

**Comment by bmueller-sykes** [comment]
Hmm...anybody else seeing this? It turns out I was getting the mis-reported browser info on a VM install of MSEdge. On a native Windows 10/MSEdge install (Edge version 25.10586.0.0), it appears to be functioning properly. Maybe that means everything is okay?

**Comment by lancedikson** [comment]
@bmueller-sykes, maybe :) It would be clearer if you send to us a whole UA and the result of bowser's test.

**Comment by bmueller-sykes** [comment]
Yeah, I'm pretty convinced this was a problem with the VM. It was wonky in a lot of other ways, too.
