### ISSUE TITLE
Samsung Galaxy S7 Edge not recognised

### ISSUE THREAD

**Issue by JenGL** [ded/bowser#131]
Samsung Galaxy S7 default browser is not recognised as android !

**Comment by lancedikson** [comment]
@JenGL, could you detect UA of S7 and send it to us, please? You can do it with [useragentstring.com](http://www.useragentstring.com/).

**Comment by JenGL** [comment]
Sorry it seems that now it works you can close this O_o
Il 15/apr/2016 06:00 PM, "Denis Demchenko" <notifications@github.com> ha
scritto:

**Comment by lancedikson** [comment]
Ok, nice
