### ISSUE TITLE
SlimerJS detection

### ISSUE THREAD

**Issue by zendre4** [ded/bowser#141]
Hello,

I use SlimerJS in parallel with PhantomJS, and I have noticed what detection of SlimerJS was not implemented in this plug-ins.

Can you implement this ?

**Comment by lancedikson** [comment]
Hello, @zendre4. Yeah, we can do it. Wait for the next minor release at this week.

Note for me: default Slimmer's UA looks like `Mozilla/5.0 (X11; Linux x86_64; rv:21.0) Gecko/20100101 SlimerJS/0.7`.

**Comment by zendre4** [comment]
Thanks!
