### ISSUE TITLE
Chromium (Linux) is not set as a-type browser

### ISSUE THREAD

**Issue by bryanspears** [ded/bowser#142]
`window.navigator.userAgent` of the browser is:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/50.0.2661.102 Chrome/50.0.2661.102 Safari/537.36`

 And it's detected like a:
`{ name: 'Chromium',
  chromium: true,
  version: '50.0',
  blink: true,
  linux: true,
  x: true }`

And that `x: true` is a problem. It should be `a: true` as it has all the capabilities of Chrome 50.0.

**Comment by lancedikson** [comment]
Yeah, good catch, thanks. I'll fix it.
