### ISSUE TITLE
IE8 - Object doesn't support this property or method

### ISSUE THREAD

**Issue by phillipsnick** [ded/bowser#147]
I'm building an incompatible browser message using this library, but I can't get IE8 to work with the `isUnsupportedBrowser` method due to what seems to be an issue inside `compareVersions`.

Browser is IE 8.0.7600.16385

<img width="627" alt="screen shot 2016-07-26 at 13 42 11" src="https://cloud.githubusercontent.com/assets/2021654/17138141/c8034bc2-5336-11e6-9097-aa196b9564eb.png">

Line 465-468 is 

```js
return map(version.split("."), function (chunk) {
  return new Array(20 - chunk.length).join("0") + chunk;
}).reverse();
```

My test code can be found here: http://lsconnect.co.uk/ie/

Which is simply

```
if (bowser.isUnsupportedBrowser({
    msie: '10.0',
    firefox: '46',
    chrome: '50',
    safari: '8.1',
    opera: '38'
})) {
  alert('Unsupported');
} else {
  alert('Supported');
}
```

I have tried to debug the code but haven't made much progress with the exact cause.

**Comment by maksimr** [comment]
Problem in function `map`

```js
  function map(arr, iterator) {
    var result = [], i;
    if (Array.prototype.map) {
      return Array.prototype.map.call(arr, iterator);
    }
    for (i = 0; i < arr.length; i++) {
      result = iterator(arr[i]); // WE SHOULD PUSH RESULT OF ITERATOR TO VARIABLE result 
    }
    return result;
  }
```

**Comment by phillipsnick** [comment]
Works perfectly!

**Comment by lancedikson** [comment]
Yeah, thank you @phillipsnick and @maksimr. The patch will be released today or maybe tomorrow.
