### ISSUE TITLE
Detect Samsung Internet for Android 

### ISSUE THREAD

**Issue by eriben** [ded/bowser#155]
In the past few months this browser has gained significant market share (>3% of total web usage) as it's being preinstalled on all Galaxy devices. Few people realize that they're not using the stock Android browser anymore.

We have run into issues with some features in this browser and desperately need to detect it. For now we've written an edge case outside of bowser but this should be thoroughly vetted by the community...

Here's a sample user agent:

Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-G925F Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36

...and here's the pull request: #156

**Comment by lancedikson** [comment]
fixed in the 1.4.5 release, thanks for the PR 👍
