### ISSUE TITLE
check returns true for IE 11 when run in Chrome 53

### ISSUE THREAD

**Issue by mnn** [ded/bowser#159]
`window.navigator.userAgent` of the browser is:
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36`

```
bowser.check({msie: '11'})
> true
bowser.chrome
> true
```

I am confused, am I doing something wrong here?

Package version is 1.4.5 - fresh from bower (but it reported some discrepancy in version numbers - in your bower file is 1.4.1).

**Comment by lancedikson** [comment]
Hi, @mnn! Sorry for my absence! 
It's all about `strictMode` for the `.check()` method. So, the author of the strict mode complains:

> The only case the strictMode should cover, when current browser wasn't passed in minVersions object. The core case: "I don't support IE10, so I have to pass {msie: 11} with first argument". So if I use firefox in this case, then it's ok. The second case is when i want to specify strictly the browsers list. In this case, when the current browser not in minVersions object, then it is not supported. The strict mode is for the second case, that in my opinion is not so common as first...

So, if you have different browser and don't use the strict mode, the browser will pass check. If you have settled strict mode flag it would affect on the checking process. Is it clear now? I think we should explain it in the docs, don't we?

**Comment by mnn** [comment]
Oh, thank you for the explanation. I mistakenly thought that `check` will return `false` for other browsers (not specified in `minVersions`), but it does so only when in strict mode.

**Comment by mnn** [comment]
My attempt at improving the help text - #162. Closing this as resolved.
