### ISSUE TITLE
Bower mismatch

### ISSUE THREAD

**Issue by IbeVanmeenen** [ded/bowser#161]
Release version of bowser is not updated in bower.json.

> Mismatch Version declared in the json (1.4.1) is different than the resolved one (1.4.5)

**Comment by lancedikson** [comment]
@IbeVanmeenen, hi! Thanks, I've already got it and it will be fixed in a few days.

**Comment by IbeVanmeenen** [comment]
Thanks 👌

**Comment by lancedikson** [comment]
Done
