### ISSUE TITLE
README: chrome examples should used string for version number

### ISSUE THREAD

**Issue by tavelli** [ded/bowser#165]
in the README chrome versions are using a number type, but the library seems to expect a string, like shown in the IE examples.

so when something like example is run:

``` javascript
bowser.check({chrome: 45}, window.navigator.userAgent); // true
```

browser throws error "Uncaught TypeError: version.split is not a function".  

When **chrome:"45"** is used, everything seems to work fine.

**Comment by lancedikson** [comment]
Thanks, @tavelli. I fixed the docs and added throwing an understandable error in that case.
