### ISSUE TITLE
When installing using bower in Visual Studio, the most recent version to install is 1.0.0

### ISSUE THREAD

**Issue by SwintDC** [ded/bowser#171]
The project URL seems to be correct: git://github.com/ded/bowser.git

But the version in the package.json of .bower.json is 1.0.0 and the source file also seems to be an old version. It seems like only the tags starting with v.. (like v1.0.0) are accessible through bower in Visual Studio.

![image](https://cloud.githubusercontent.com/assets/18047780/21719497/734ab174-d41e-11e6-8282-71db0fefc48f.png)

**Comment by SwintDC** [comment]
When using the gulp-bower npm package though a more recent version is downloaded:
![image](https://cloud.githubusercontent.com/assets/18047780/21719680/5464c802-d41f-11e6-8cf5-87d0a280c0d4.png)

**Comment by lancedikson** [comment]
@SwintDC, what kind of bower do you use? Because, I just typed `bower info bowser` in my terminal and had seen that:
```
...
Available versions:
  - 1.6.0
  - 1.5.0
  - 1.4.6
  - 1.4.5
  - 1.4.4
  - 1.4.3
  - 1.4.2
  - 1.4.1
  - 1.4.0
...
```

**Comment by SwintDC** [comment]
@lancedikson, the kind that comes preinstalled with Visual Studio 2015. But it's not really a problem anymore for me, I thought I'd just let you know... Other people may also encounter this using Visual Studio 2015... Not that big a problem ...

**Comment by lancedikson** [comment]
@SwintDC, got it. Thanks for the notice. I'll close the issue. If someone catch the same problem, he/she find the issue easy, I guess :)
