### ISSUE TITLE
Consider more strict jshint settings

### ISSUE THREAD

**Issue by Xiphe** [ded/bowser#51]
Hey @ded 

We talked about this, a long time ago and i totally respect that your project is written in the code style you like and love.
Unfortunately i'm not able to switch back to your main branch since our build tool is more strict about the javascript syntax it can handle, and breaks when trying to minify bowser.

If you're ok with it, i will try to tighten up your jshint config until i pass our pipeline and then open a PR. However if that's not an option for you i'll just stick to our fork.

kind regards, Hannes.

**Comment by lancedikson** [comment]
I guess, we can close this.
