### ISSUE TITLE
Safari on iPad shows as "iPad" instead of Safari.

### ISSUE THREAD

**Issue by lopesc** [ded/bowser#55]
In my app, I want to check which browser is being used. 

bowser.name generally gives me the name of the browser, except for Safari on iPad, which returns "iPad" as the name.  Why is this?

**Comment by krom-xr** [comment]
+1 and in iOS bowser.safari - return undefined

**Comment by campwise** [comment]
+1 - just downloaded 0.7.3 last week and the iPad Safari issue is still present (have verified in both safari 5.1 and 6) as well as Safari iPhone.

**Comment by campwise** [comment]
Not only is the name for both iPad and iPhone incorrect, but I believe the safari browser version is incorrect also (?)
![image1](https://cloud.githubusercontent.com/assets/9702325/8623733/1b6c5a28-2701-11e5-85b1-984aca800d7c.jpg)
![image2](https://cloud.githubusercontent.com/assets/9702325/8623735/1b709340-2701-11e5-9daf-789f7a7d2668.jpg)
![image3](https://cloud.githubusercontent.com/assets/9702325/8623734/1b6e4b94-2701-11e5-8a25-dd48abbef0e5.jpg)

**Comment by campwise** [comment]
If I use these Safari iPhone user agent strings I can get the correct browser version number:

iPhone 5:
Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3

iPhone 6:
Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25

**Comment by mhulse** [comment]
+1 Noticing this as well. Great script though!

**Comment by lopesc** [comment]
Hey @everyone I created a PR with a fix for this issue - please review! 
https://github.com/ded/bowser/pull/111

**Comment by jacksonrayhamilton** [comment]
+1

**Comment by lancedikson** [comment]
Hey guys, we continue working on Bowser and I have a solution for you: checkout [develop branch](https://github.com/ded/bowser/tree/develop) please to see it. Now we detect the real browser's name on iOS. It will be released soon.
