### ISSUE TITLE
README has bowser.msie

### ISSUE THREAD

**Issue by grassick** [ded/bowser#56]
But it should be bowser.browser.msie in an npm environment

**Comment by mattdell** [comment]
+1

I found that very confusing at first.

**Comment by vvo** [comment]
see #77 cc @ded

**Comment by mattdell** [comment]
Thanks for that @vvo. Glad to see it's been raised!

**Comment by ded** [comment]
this is all mostly related to the confusing export — which i'm hoping to have fixed shortly

**Comment by ded** [comment]
`require('bowser')` now works exactly as it does on the browser as it does in Node :)
