### ISSUE TITLE
Firefox for Android is detected as Firefox OS

### ISSUE THREAD

**Issue by cvan** [ded/bowser#59]
> Mozilla/5.0 (Android; Mobile; rv:30.0) Gecko/30.0 Firefox/30.0

Because of https://github.com/ded/bowser/blob/1a70355/bowser.js#L92

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference and http://lawrencemandel.com/2012/07/27/decision-made-firefox-os-user-agent-string/

**Comment by lancedikson** [comment]
Already fixed
