### ISSUE TITLE
Return Browser as Variable

### ISSUE THREAD

**Issue by villanus** [ded/bowser#60]
Right now you have functions like if browsers = chrome then.
It would be nice to just write the browser to a variable for use later.   This is extremely useful if you add a class to body with the browser name (sorta like modernizr).  

some like this
var browser = detect.browser

**Comment by jasonkarns** [comment]
I'm completely lost by what you're asking for. The results are indeed assigned to an object:

```js
var browser = require('bowser')
browser.name
```

**Comment by ded** [comment]
indeed:
``` js
document.body.classList.add('browser-' + require('bowser').name)
```
