### ISSUE TITLE
Support of new Safari on IOS 8 User agent

### ISSUE THREAD

**Issue by oanguenot** [ded/bowser#61]
Latest Safari on IOS 8 is not supported currently with bower

Here is the new user agent to add:
Mozilla/5.0 (ipad; CPU OS 8_0 like Mac OS X) AppleWebKit/600.1.4
(KHTML, like Gecko) Version/8.0 Mobile/12A365 Safari/600.1.4

Thanks in advance,

**Comment by lancedikson** [comment]
Now it's ok.
