### ISSUE TITLE
Doesn't work for Moto X

### ISSUE THREAD

**Issue by schickling** [ded/bowser#64]
Moto X on Chrome reports the following UserAgent:

```Mozilla/5.0 (Linux; Android 4.4.4; XT1032 Build/KXB21.14-L1.40) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.102 Mobile Safari/537.36```

**Comment by lancedikson** [comment]
It's ok for me: 

```
{ name: 'Chrome',
  chrome: true,
  version: '38.0',
  webkit: true,
  android: true,
  osversion: '4.4.4',
  mobile: true,
  a: true }
```
