### ISSUE TITLE
JavaScript error due to missing semicolon

### ISSUE THREAD

**Issue by mahboob-awan** [ded/bowser#70]
Please add semicolon at the end of minified file because missing semicolon caused javascript error at following place:

```
!function(e,t){ /* bowser minified code*/}) 

/*!
 * jQuery Migrate - v1.2.1 - 2013-05-08
 * https://github.com/jquery/jquery-migrate
 * Copyright 2005, 2013 jQuery Foundation, Inc. and other contributors; Licensed MIT
 */
(function( jQuery, window, undefined ) {...})( jQuery, window );

```

**Comment by jasonkarns** [comment]
the semicolon is not required and would not cause a js error on its own. it could cause an error if concatenating with other scripts. if that is the case, I would recommend using a tool that concatenates intelligently by inserting semicolons between concatenated scripts.

**Comment by ded** [comment]
same.

**Comment by uaoleg** [comment]
Is it a problem to add a semicolon and to reduce the amount of butthurt of lots of people?
