### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by marcelbuesing** [ded/bowser#79]
Add a LICENSE file.

**Comment by nhodges** [comment]
Came here to post this same thing. @ded how may we use your software?

Thanks!

**Comment by marcelbuesing** [comment]
@nhodges it's mentioned in the code, [this](https://github.com/ded/bowser/blob/master/src/copyright.js) is prepended. Nevertheless it would still be great to see it immediately.

**Comment by kottmann** [comment]
Yes, please add a LICENSE file to it and maybe mentioned it in the README file. Many of your users need to check if the license of your library is suitable for the inclusion in their projects.

Should I send you a pull request?

**Comment by ded** [comment]
hi @marcelbuesing @nhodges @kottmann this has been taken care of! :+1: cheers
