### ISSUE TITLE
How can I detect a custom user agent string from GhostInspector?

### ISSUE THREAD

**Issue by nathanpitman** [ded/bowser#80]
I'm using the wonderful Ghost Inspector (https://ghostinspector.com/) to run automated tests on my app and need to ensure that the requests from them bypass my browser minimum requirements check, in Ghost Inspector you can set a custom user agent string but how would I set about bypassing the browser check if that's present... currently I have:

```
if ((bowser.msie && bowser.version < 8) || (!bowser.ios && !training.hasFlash())) {
    if (typeof unsupported_redirect_path!="undefined") {
        window.location = unsupported_redirect_path;
    }
}
```

**Comment by lancedikson** [comment]
You could use _detect function of the Bowser like this:

```
var window.bowser = require('bowser');
var result = bowser._detect(customUA);
```
