### ISSUE TITLE
Support detection of Microsoft Spartan

### ISSUE THREAD

**Issue by nzrower** [ded/bowser#81]
http://en.wikipedia.org/wiki/Spartan_%28browser%29

'Spartan" is the codename of a web browser under development by Microsoft. Officially unveiled on January 21, 2015, and first publicly released as a preview on March 30, 2015, it will replace Internet Explorer as the default browser of Windows 10 PCs, smartphones and tablets.'

Is support for detection of Spartan planned?
Or can this be achieved using the existing code?

Thanks in advance.

**Comment by marksomnian** [comment]
Edge (Spartan) can be detected using `bowser.msedge`
