### ISSUE TITLE
IE Compatibility Mode

### ISSUE THREAD

**Issue by tanx8** [ded/bowser#90]
When you are using IE 10 in Compatibility mode, userAgent string contains 'MSIE 7.0' and 'Trident/6.0'
Bowser is detecting it as IE 7.
Not sure if this is an intended feature as it's displayed in compatibility, but the actual IE version is IE10

**Comment by ded** [comment]
I believe it is intended to be this way — although I can see both sides (for your case). Users can switch their browser to be "compatible" so this keeps that in check.
