### ISSUE TITLE
Detect Microsoft Edge

### ISSUE THREAD

**Issue by royaldark** [ded/bowser#91]
Since Windows 10 will be released in one month, it would be nice if detection of Microsoft's newest browser could be included before then. Here is an example UA string [from MSDN](https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx):

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0`

**Comment by campwise** [comment]
Already done: https://github.com/ded/bowser/pull/85

**Comment by royaldark** [comment]
Sorry, missed it. Thanks!

**Comment by ded** [comment]
:)

**Comment by blainemuri** [comment]
This should really be placed in the documentation as one of the listed examples
