### ISSUE TITLE
Hello, China?

### ISSUE THREAD

**Issue by dilfish** [ded/bowser#92]
Does that sound a little racist or it's just an emphasizing of the distressful fact?

**Comment by stenmuchow** [comment]
how does this have anything to do with race?

https://www.modern.ie/en-us/ie6countdown

China - largest IE6 user in the world...

**Comment by ded** [comment]
China is a country, not a race. If anything it's "regionalist" based on actual data. And also yes, it's a joke based on the distressful fact.

**Comment by daiheitan** [comment]
I'm from China and I really love your sense of humor, dude. XD

Everyone hates IE6
