### ISSUE TITLE
Define license of the library

### ISSUE THREAD

**Issue by mkotsur** [ded/bowser#95]
For some commercial projects it is important to know licenses of all libraries that are included into distribution. What is the license of this product?

**Comment by ded** [comment]
@mkotsur I'll make it more obvious. Right now it's included in the source https://github.com/ded/bowser/blob/master/src/copyright.js

and appended to the built file. https://github.com/ded/bowser/blob/master/bowser.js#L4

**Comment by ded** [comment]
added :+1: https://github.com/ded/bowser/blob/master/LICENSE
