### ISSUE TITLE
Expose OS Detection api

### ISSUE THREAD

**Issue by joshontheweb** [ded/bowser#98]
It would be really cool if the Operating System detection was part of the public api.  I'm using bowser to log information for bug reports and ideally I'd know: OS, OS version, Browser, Browser Version.

**Comment by rmosolgo** [comment]
Same, I've had great luck with dowser so far in determining browser, would be nice to throw OS in there too (right now I'm trying to detect Windows vs OSX / Linux)

**Comment by ded** [comment]
This has been expressed by a few others (off this thread). This feels like a natural progression for this library so I'm sure we can figure something out.

**Comment by NemoAlex** [comment]
+1 Need this too.

**Comment by wbinnssmith** [comment]
I wonder what a good api for the os would be. Would it be like the `android` and `ios` flags — OSes that are already exposed themselves — with their own individual properties on the results object? It could arguably also be like `name`, which there can only ever be one of, which points to a string representation of the OS.

**Comment by campwise** [comment]
I will be out of the office until Monday October 12th. If you need a more timely response to an issue, please call the office at 540.433.3939


THANKS

**Comment by mhulse** [comment]
+1, and thanks for this code.
