### ISSUE TITLE
Please add support for Firefox for iOS

### ISSUE THREAD

**Issue by st3fan** [ded/bowser#99]
You can find our UA strings here:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference#Firefox_for_iOS

Firefox for iOS uses the same WKWebView as Safari for iOS. In theory we are on parity with Safari functionality.

Thanks!

**Comment by lancedikson** [comment]
Will be at the next minor release :)

**Comment by taylorstine** [comment]
Just to check, has this been released? I'm having trouble rendering flexbox on firefox for iOS.
